name: Run tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev, fix ]

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [8.1, 8.0, 7.4]
                laravel: [8.*, 9.*]
                os: [ubuntu-latest, windows-latest]
                stability: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 8.*
                      testbench: 6.*
                    - laravel: 9.*
                      testbench: 7.*
                exclude:
                    - laravel: 9.*
                      php: 7.*

        name: PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }} -${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, exif, iconv, fileinfo
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest

            - name: Execute pest tests
              run: vendor/bin/pest